services:
  frontend:
    image: ghcr.io/kevinlhuillier/wod-tracker-front:main
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://kevinlhuillier.fr/api

  server:
    image: ghcr.io/kevinlhuillier/wod-tracker-back:main
    ports:
      - "8080:8080"
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wodapp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=a!=sds{sdsd896Fzsd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a!=sds{sdsd896Fzsd
      POSTGRES_DB: wodapp
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
